pull_request_rules:
  - name: comment-pre-commit-failure
    description: Comment on PR when pre-commit check fails
    conditions:
      - check-failure=Run pre-commit hooks
      - -closed
      - -draft
    actions:
      comment:
        message: |
          Hi @{{author}}, the pre-commit checks have failed. Please run:

          ```bash
          uv pip install pre-commit
          pre-commit install
          pre-commit run --all-files
          ```

          Then, commit the changes and push to your branch.

          For future commits, `pre-commit` will run automatically on changed files before each commit.

