# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tokenizerpb import tokenizer_pb2 as tokenizerpb_dot_tokenizer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tokenizerpb/tokenizer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TokenizationServiceStub(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/tokenization.TokenizationService/Tokenize',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.RenderChatTemplate = channel.unary_unary(
                '/tokenization.TokenizationService/RenderChatTemplate',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.FromString,
                _registered_method=True)
        self.RenderChatAndTokenize = channel.unary_unary(
                '/tokenization.TokenizationService/RenderChatAndTokenize',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
                _registered_method=True)
        self.InitializeTokenizer = channel.unary_unary(
                '/tokenization.TokenizationService/InitializeTokenizer',
                request_serializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.SerializeToString,
                response_deserializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.FromString,
                _registered_method=True)


class TokenizationServiceServicer(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    def Tokenize(self, request, context):
        """Tokenize converts a text input to token IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderChatTemplate(self, request, context):
        """RenderChatTemplate renders a chat template with the given messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenderChatAndTokenize(self, request, context):
        """RenderChatAndTokenize renders a chat template and tokenizes the result in a single round-trip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeTokenizer(self, request, context):
        """InitializeTokenizer initializes the tokenizer for a specific model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenizationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.SerializeToString,
            ),
            'RenderChatTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderChatTemplate,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.SerializeToString,
            ),
            'RenderChatAndTokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.RenderChatAndTokenize,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.SerializeToString,
            ),
            'InitializeTokenizer': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeTokenizer,
                    request_deserializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.FromString,
                    response_serializer=tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tokenization.TokenizationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tokenization.TokenizationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TokenizationService(object):
    """TokenizationService defines the gRPC service for tokenization
    """

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/Tokenize',
            tokenizerpb_dot_tokenizer__pb2.TokenizeRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderChatTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/RenderChatTemplate',
            tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.ChatTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenderChatAndTokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/RenderChatAndTokenize',
            tokenizerpb_dot_tokenizer__pb2.ChatTemplateRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.TokenizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeTokenizer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tokenization.TokenizationService/InitializeTokenizer',
            tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerRequest.SerializeToString,
            tokenizerpb_dot_tokenizer__pb2.InitializeTokenizerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
