// Copyright 2025 The llm-d Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/tokenizerpb/tokenizer.proto

package tokenizerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TokenizationService_InitializeTokenizer_FullMethodName = "/tokenization.TokenizationService/InitializeTokenizer"
	TokenizationService_Render_FullMethodName              = "/tokenization.TokenizationService/Render"
	TokenizationService_RenderChat_FullMethodName          = "/tokenization.TokenizationService/RenderChat"
)

// TokenizationServiceClient is the client API for TokenizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TokenizationService defines the gRPC service for tokenization
type TokenizationServiceClient interface {
	// InitializeTokenizer initializes the tokenizer for a specific model
	InitializeTokenizer(ctx context.Context, in *InitializeTokenizerRequest, opts ...grpc.CallOption) (*InitializeTokenizerResponse, error)
	// Render renders (tokenizes) a text input
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
	// RenderChat renders a chat conversation to tokens and offsets
	RenderChat(ctx context.Context, in *RenderChatRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type tokenizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenizationServiceClient(cc grpc.ClientConnInterface) TokenizationServiceClient {
	return &tokenizationServiceClient{cc}
}

func (c *tokenizationServiceClient) InitializeTokenizer(ctx context.Context, in *InitializeTokenizerRequest, opts ...grpc.CallOption) (*InitializeTokenizerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeTokenizerResponse)
	err := c.cc.Invoke(ctx, TokenizationService_InitializeTokenizer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, TokenizationService_Render_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenizationServiceClient) RenderChat(ctx context.Context, in *RenderChatRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenderResponse)
	err := c.cc.Invoke(ctx, TokenizationService_RenderChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenizationServiceServer is the server API for TokenizationService service.
// All implementations must embed UnimplementedTokenizationServiceServer
// for forward compatibility.
//
// TokenizationService defines the gRPC service for tokenization
type TokenizationServiceServer interface {
	// InitializeTokenizer initializes the tokenizer for a specific model
	InitializeTokenizer(context.Context, *InitializeTokenizerRequest) (*InitializeTokenizerResponse, error)
	// Render renders (tokenizes) a text input
	Render(context.Context, *RenderRequest) (*RenderResponse, error)
	// RenderChat renders a chat conversation to tokens and offsets
	RenderChat(context.Context, *RenderChatRequest) (*RenderResponse, error)
	mustEmbedUnimplementedTokenizationServiceServer()
}

// UnimplementedTokenizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenizationServiceServer struct{}

func (UnimplementedTokenizationServiceServer) InitializeTokenizer(context.Context, *InitializeTokenizerRequest) (*InitializeTokenizerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeTokenizer not implemented")
}
func (UnimplementedTokenizationServiceServer) Render(context.Context, *RenderRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Render not implemented")
}
func (UnimplementedTokenizationServiceServer) RenderChat(context.Context, *RenderChatRequest) (*RenderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenderChat not implemented")
}
func (UnimplementedTokenizationServiceServer) mustEmbedUnimplementedTokenizationServiceServer() {}
func (UnimplementedTokenizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeTokenizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenizationServiceServer will
// result in compilation errors.
type UnsafeTokenizationServiceServer interface {
	mustEmbedUnimplementedTokenizationServiceServer()
}

func RegisterTokenizationServiceServer(s grpc.ServiceRegistrar, srv TokenizationServiceServer) {
	// If the following call panics, it indicates UnimplementedTokenizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TokenizationService_ServiceDesc, srv)
}

func _TokenizationService_InitializeTokenizer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeTokenizerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).InitializeTokenizer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_InitializeTokenizer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).InitializeTokenizer(ctx, req.(*InitializeTokenizerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_Render_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenizationService_RenderChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenizationServiceServer).RenderChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TokenizationService_RenderChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenizationServiceServer).RenderChat(ctx, req.(*RenderChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenizationService_ServiceDesc is the grpc.ServiceDesc for TokenizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenization.TokenizationService",
	HandlerType: (*TokenizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeTokenizer",
			Handler:    _TokenizationService_InitializeTokenizer_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _TokenizationService_Render_Handler,
		},
		{
			MethodName: "RenderChat",
			Handler:    _TokenizationService_RenderChat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tokenizerpb/tokenizer.proto",
}
