// Copyright 2025 The llm-d Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/tokenizerpb/tokenizer.proto

package tokenizerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatMessage represents a single message in a conversation
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // Role of the message (e.g., "user", "assistant", "system")
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Content of the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Value represents a generic value that can be string, number, bool, or list
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	//	*Value_ListValue
	//	*Value_StructValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetStructValue() *StructValue {
	if x != nil {
		if x, ok := x.Value.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,4,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *StructValue `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_NumberValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_ListValue) isValue_Value() {}

func (*Value_StructValue) isValue_Value() {}

// ListValue represents a list of values
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{2}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// StructValue represents a structured value (key-value pairs)
type StructValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructValue) Reset() {
	*x = StructValue{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructValue) ProtoMessage() {}

func (x *StructValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructValue.ProtoReflect.Descriptor instead.
func (*StructValue) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{3}
}

func (x *StructValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// InitializeTokenizerRequest represents a request to initialize tokenizer for a model
type InitializeTokenizerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLocal       bool                   `protobuf:"varint,1,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`                  // Whether the model is local (default: true)
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`                                      // The model ID or path (HF model ID, local directory path, or path to tokenizer file)
	Revision      *string                `protobuf:"bytes,3,opt,name=revision,proto3,oneof" json:"revision,omitempty"`                          // Model revision (optional)
	Token         *string                `protobuf:"bytes,4,opt,name=token,proto3,oneof" json:"token,omitempty"`                                // Hugging Face token for private models (optional)
	DownloadDir   *string                `protobuf:"bytes,5,opt,name=download_dir,json=downloadDir,proto3,oneof" json:"download_dir,omitempty"` // Directory to download the model (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeTokenizerRequest) Reset() {
	*x = InitializeTokenizerRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeTokenizerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeTokenizerRequest) ProtoMessage() {}

func (x *InitializeTokenizerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeTokenizerRequest.ProtoReflect.Descriptor instead.
func (*InitializeTokenizerRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeTokenizerRequest) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *InitializeTokenizerRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *InitializeTokenizerRequest) GetRevision() string {
	if x != nil && x.Revision != nil {
		return *x.Revision
	}
	return ""
}

func (x *InitializeTokenizerRequest) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *InitializeTokenizerRequest) GetDownloadDir() string {
	if x != nil && x.DownloadDir != nil {
		return *x.DownloadDir
	}
	return ""
}

// InitializeTokenizerResponse represents the response from tokenizer initialization
type InitializeTokenizerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the initialization was successful
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if initialization failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeTokenizerResponse) Reset() {
	*x = InitializeTokenizerResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeTokenizerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeTokenizerResponse) ProtoMessage() {}

func (x *InitializeTokenizerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeTokenizerResponse.ProtoReflect.Descriptor instead.
func (*InitializeTokenizerResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{5}
}

func (x *InitializeTokenizerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitializeTokenizerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// RenderRequest represents a request to render (tokenize) a text input
type RenderRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Text             string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                                    // The text input to render/tokenize
	ModelName        string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                         // The name of the model to use for tokenization
	AddSpecialTokens bool                   `protobuf:"varint,3,opt,name=add_special_tokens,json=addSpecialTokens,proto3" json:"add_special_tokens,omitempty"` // Whether to add special tokens during tokenization
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{6}
}

func (x *RenderRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RenderRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RenderRequest) GetAddSpecialTokens() bool {
	if x != nil {
		return x.AddSpecialTokens
	}
	return false
}

// RenderChatRequest represents a request to render a chat conversation
type RenderChatRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Conversation              []*ChatMessage         `protobuf:"bytes,1,rep,name=conversation,proto3" json:"conversation,omitempty"`                                                                                                                   // The conversation messages (array of role/content pairs)
	Tools                     []*Value               `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`                                                                                                                                 // Tools available to the conversation (arbitrary values)
	Documents                 []*Value               `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`                                                                                                                         // Documents related to the conversation (arbitrary values)
	ChatTemplate              *string                `protobuf:"bytes,4,opt,name=chat_template,json=chatTemplate,proto3,oneof" json:"chat_template,omitempty"`                                                                                         // The chat template to use
	ReturnAssistantTokensMask *bool                  `protobuf:"varint,5,opt,name=return_assistant_tokens_mask,json=returnAssistantTokensMask,proto3,oneof" json:"return_assistant_tokens_mask,omitempty"`                                             // Whether to return assistant token mask
	ContinueFinalMessage      *bool                  `protobuf:"varint,6,opt,name=continue_final_message,json=continueFinalMessage,proto3,oneof" json:"continue_final_message,omitempty"`                                                              // Whether to continue the final message
	AddGenerationPrompt       *bool                  `protobuf:"varint,7,opt,name=add_generation_prompt,json=addGenerationPrompt,proto3,oneof" json:"add_generation_prompt,omitempty"`                                                                 // Whether to add generation prompt
	ChatTemplateKwargs        map[string]*Value      `protobuf:"bytes,8,rep,name=chat_template_kwargs,json=chatTemplateKwargs,proto3" json:"chat_template_kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional chat template arguments
	ModelName                 string                 `protobuf:"bytes,9,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`                                                                                                        // The name of the model to use for tokenization
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RenderChatRequest) Reset() {
	*x = RenderChatRequest{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderChatRequest) ProtoMessage() {}

func (x *RenderChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderChatRequest.ProtoReflect.Descriptor instead.
func (*RenderChatRequest) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{7}
}

func (x *RenderChatRequest) GetConversation() []*ChatMessage {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *RenderChatRequest) GetTools() []*Value {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *RenderChatRequest) GetDocuments() []*Value {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RenderChatRequest) GetChatTemplate() string {
	if x != nil && x.ChatTemplate != nil {
		return *x.ChatTemplate
	}
	return ""
}

func (x *RenderChatRequest) GetReturnAssistantTokensMask() bool {
	if x != nil && x.ReturnAssistantTokensMask != nil {
		return *x.ReturnAssistantTokensMask
	}
	return false
}

func (x *RenderChatRequest) GetContinueFinalMessage() bool {
	if x != nil && x.ContinueFinalMessage != nil {
		return *x.ContinueFinalMessage
	}
	return false
}

func (x *RenderChatRequest) GetAddGenerationPrompt() bool {
	if x != nil && x.AddGenerationPrompt != nil {
		return *x.AddGenerationPrompt
	}
	return false
}

func (x *RenderChatRequest) GetChatTemplateKwargs() map[string]*Value {
	if x != nil {
		return x.ChatTemplateKwargs
	}
	return nil
}

func (x *RenderChatRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

// RenderResponse represents the response from rendering/tokenizing
type RenderResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InputIds     []uint32               `protobuf:"varint,1,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`     // Token IDs for the input
	Success      bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                              // Whether the request was successful
	ErrorMessage string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // Error message if the request failed
	// Direct array of [start, end] pairs
	OffsetPairs   []uint32 `protobuf:"varint,4,rep,packed,name=offset_pairs,json=offsetPairs,proto3" json:"offset_pairs,omitempty"` // Flattened array of [start, end, start, end, ...]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_tokenizerpb_tokenizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_api_tokenizerpb_tokenizer_proto_rawDescGZIP(), []int{8}
}

func (x *RenderResponse) GetInputIds() []uint32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *RenderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenderResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RenderResponse) GetOffsetPairs() []uint32 {
	if x != nil {
		return x.OffsetPairs
	}
	return nil
}

var File_api_tokenizerpb_tokenizer_proto protoreflect.FileDescriptor

const file_api_tokenizerpb_tokenizer_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/tokenizerpb/tokenizer.proto\x12\ftokenization\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xf5\x01\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x128\n" +
	"\n" +
	"list_value\x18\x04 \x01(\v2\x17.tokenization.ListValueH\x00R\tlistValue\x12>\n" +
	"\fstruct_value\x18\x05 \x01(\v2\x19.tokenization.StructValueH\x00R\vstructValueB\a\n" +
	"\x05value\"8\n" +
	"\tListValue\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.tokenization.ValueR\x06values\"\x9c\x01\n" +
	"\vStructValue\x12=\n" +
	"\x06fields\x18\x01 \x03(\v2%.tokenization.StructValue.FieldsEntryR\x06fields\x1aN\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x1aInitializeTokenizerRequest\x12\x19\n" +
	"\bis_local\x18\x01 \x01(\bR\aisLocal\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x1f\n" +
	"\brevision\x18\x03 \x01(\tH\x00R\brevision\x88\x01\x01\x12\x19\n" +
	"\x05token\x18\x04 \x01(\tH\x01R\x05token\x88\x01\x01\x12&\n" +
	"\fdownload_dir\x18\x05 \x01(\tH\x02R\vdownloadDir\x88\x01\x01B\v\n" +
	"\t_revisionB\b\n" +
	"\x06_tokenB\x0f\n" +
	"\r_download_dir\"\\\n" +
	"\x1bInitializeTokenizerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"p\n" +
	"\rRenderRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12,\n" +
	"\x12add_special_tokens\x18\x03 \x01(\bR\x10addSpecialTokens\"\xe2\x05\n" +
	"\x11RenderChatRequest\x12=\n" +
	"\fconversation\x18\x01 \x03(\v2\x19.tokenization.ChatMessageR\fconversation\x12)\n" +
	"\x05tools\x18\x02 \x03(\v2\x13.tokenization.ValueR\x05tools\x121\n" +
	"\tdocuments\x18\x03 \x03(\v2\x13.tokenization.ValueR\tdocuments\x12(\n" +
	"\rchat_template\x18\x04 \x01(\tH\x00R\fchatTemplate\x88\x01\x01\x12D\n" +
	"\x1creturn_assistant_tokens_mask\x18\x05 \x01(\bH\x01R\x19returnAssistantTokensMask\x88\x01\x01\x129\n" +
	"\x16continue_final_message\x18\x06 \x01(\bH\x02R\x14continueFinalMessage\x88\x01\x01\x127\n" +
	"\x15add_generation_prompt\x18\a \x01(\bH\x03R\x13addGenerationPrompt\x88\x01\x01\x12i\n" +
	"\x14chat_template_kwargs\x18\b \x03(\v27.tokenization.RenderChatRequest.ChatTemplateKwargsEntryR\x12chatTemplateKwargs\x12\x1d\n" +
	"\n" +
	"model_name\x18\t \x01(\tR\tmodelName\x1aZ\n" +
	"\x17ChatTemplateKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.tokenization.ValueR\x05value:\x028\x01B\x10\n" +
	"\x0e_chat_templateB\x1f\n" +
	"\x1d_return_assistant_tokens_maskB\x19\n" +
	"\x17_continue_final_messageB\x18\n" +
	"\x16_add_generation_prompt\"\x8f\x01\n" +
	"\x0eRenderResponse\x12\x1b\n" +
	"\tinput_ids\x18\x01 \x03(\rR\binputIds\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12!\n" +
	"\foffset_pairs\x18\x04 \x03(\rR\voffsetPairs2\x93\x02\n" +
	"\x13TokenizationService\x12j\n" +
	"\x13InitializeTokenizer\x12(.tokenization.InitializeTokenizerRequest\x1a).tokenization.InitializeTokenizerResponse\x12C\n" +
	"\x06Render\x12\x1b.tokenization.RenderRequest\x1a\x1c.tokenization.RenderResponse\x12K\n" +
	"\n" +
	"RenderChat\x12\x1f.tokenization.RenderChatRequest\x1a\x1c.tokenization.RenderResponseB=Z;github.com/llm-d/llm-d-kv-cache/api/tokenizerpb;tokenizerpbb\x06proto3"

var (
	file_api_tokenizerpb_tokenizer_proto_rawDescOnce sync.Once
	file_api_tokenizerpb_tokenizer_proto_rawDescData []byte
)

func file_api_tokenizerpb_tokenizer_proto_rawDescGZIP() []byte {
	file_api_tokenizerpb_tokenizer_proto_rawDescOnce.Do(func() {
		file_api_tokenizerpb_tokenizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tokenizerpb_tokenizer_proto_rawDesc), len(file_api_tokenizerpb_tokenizer_proto_rawDesc)))
	})
	return file_api_tokenizerpb_tokenizer_proto_rawDescData
}

var file_api_tokenizerpb_tokenizer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_tokenizerpb_tokenizer_proto_goTypes = []any{
	(*ChatMessage)(nil),                 // 0: tokenization.ChatMessage
	(*Value)(nil),                       // 1: tokenization.Value
	(*ListValue)(nil),                   // 2: tokenization.ListValue
	(*StructValue)(nil),                 // 3: tokenization.StructValue
	(*InitializeTokenizerRequest)(nil),  // 4: tokenization.InitializeTokenizerRequest
	(*InitializeTokenizerResponse)(nil), // 5: tokenization.InitializeTokenizerResponse
	(*RenderRequest)(nil),               // 6: tokenization.RenderRequest
	(*RenderChatRequest)(nil),           // 7: tokenization.RenderChatRequest
	(*RenderResponse)(nil),              // 8: tokenization.RenderResponse
	nil,                                 // 9: tokenization.StructValue.FieldsEntry
	nil,                                 // 10: tokenization.RenderChatRequest.ChatTemplateKwargsEntry
}
var file_api_tokenizerpb_tokenizer_proto_depIdxs = []int32{
	2,  // 0: tokenization.Value.list_value:type_name -> tokenization.ListValue
	3,  // 1: tokenization.Value.struct_value:type_name -> tokenization.StructValue
	1,  // 2: tokenization.ListValue.values:type_name -> tokenization.Value
	9,  // 3: tokenization.StructValue.fields:type_name -> tokenization.StructValue.FieldsEntry
	0,  // 4: tokenization.RenderChatRequest.conversation:type_name -> tokenization.ChatMessage
	1,  // 5: tokenization.RenderChatRequest.tools:type_name -> tokenization.Value
	1,  // 6: tokenization.RenderChatRequest.documents:type_name -> tokenization.Value
	10, // 7: tokenization.RenderChatRequest.chat_template_kwargs:type_name -> tokenization.RenderChatRequest.ChatTemplateKwargsEntry
	1,  // 8: tokenization.StructValue.FieldsEntry.value:type_name -> tokenization.Value
	1,  // 9: tokenization.RenderChatRequest.ChatTemplateKwargsEntry.value:type_name -> tokenization.Value
	4,  // 10: tokenization.TokenizationService.InitializeTokenizer:input_type -> tokenization.InitializeTokenizerRequest
	6,  // 11: tokenization.TokenizationService.Render:input_type -> tokenization.RenderRequest
	7,  // 12: tokenization.TokenizationService.RenderChat:input_type -> tokenization.RenderChatRequest
	5,  // 13: tokenization.TokenizationService.InitializeTokenizer:output_type -> tokenization.InitializeTokenizerResponse
	8,  // 14: tokenization.TokenizationService.Render:output_type -> tokenization.RenderResponse
	8,  // 15: tokenization.TokenizationService.RenderChat:output_type -> tokenization.RenderResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_tokenizerpb_tokenizer_proto_init() }
func file_api_tokenizerpb_tokenizer_proto_init() {
	if File_api_tokenizerpb_tokenizer_proto != nil {
		return
	}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_StructValue)(nil),
	}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_tokenizerpb_tokenizer_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tokenizerpb_tokenizer_proto_rawDesc), len(file_api_tokenizerpb_tokenizer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tokenizerpb_tokenizer_proto_goTypes,
		DependencyIndexes: file_api_tokenizerpb_tokenizer_proto_depIdxs,
		MessageInfos:      file_api_tokenizerpb_tokenizer_proto_msgTypes,
	}.Build()
	File_api_tokenizerpb_tokenizer_proto = out.File
	file_api_tokenizerpb_tokenizer_proto_goTypes = nil
	file_api_tokenizerpb_tokenizer_proto_depIdxs = nil
}
